name: Ahk2Exe
description: GitHub Action to compile AutoHotKey scripts using Ahk2Exe
author: nekocodeX, modified for AHK v2 by jaredkotoff

inputs:
  in:
    description: The path or file name of the AutoHotKey script to compile (without the .ahk extension)
    required: true
  out:
    description: The path or file name of the compiled executable (by default, an executable of the same name will be created in the path of the AutoHotKey script specified by the "in" parameter)
    required: false
    default: ''
  icon:
    description: The icon of the executable file is specified
    required: false
    default: ''

runs:
  using: composite
  steps:
    # - name: Generate Names
    #   id: names
    #   shell: bash
    #   run: |
    #     echo "in_name=${{inputs.in}}.ahk" >> $GITHUB_ENV
    #     echo "out_name=${{inputs.in}}" >> $GITHUB_ENV
    #     if ('${{inputs.out}}' -ne '') {
    #       echo "out_name=${{inputs.out}}" >> $GITHUB_ENV
    #     }
    #     echo 'icon_param=""' >> $GITHUB_ENV
    #     if ('${{inputs.icon}}' -ne '') {
    #       echo 'icon_param=" /icon ${{inputs.icon}}"' >> $GITHUB_ENV
    #     }

    - name: Generate Names
      id: names
      shell: pwsh
      run: |
        $in_name = "${{inputs.in}}.ahk"
        $out_name = "${{inputs.in}}"
        if ('${{inputs.out}}' -ne '') {
          $out_name = "${{inputs.out}}"
        }
        $icon_param = ""
        if ('${{inputs.icon}}' -ne '') {
         $icon_param = ' /icon "${{inputs.icon}}"'
        }

    - name: Extract Ahk2Exe
      shell: pwsh
      run: |
        $cwd = (Get-Item .).FullName;
        Expand-Archive -Path "$cwd\.github\actions\ahk2exe\ahk2exe-v1.1.35.00.zip" -DestinationPath "$cwd\_autohotkey\" -Force;
        Write-Output ("$cwd\_autohotkey\;" + "$cwd\_autohotkey\Compiler") | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Run Ahk2Exe_64-bit
      shell: pwsh
      run: Ahk2exe.exe /base "$cwd\_autohotkey\Compiler\AutoHotkey64.exe" /in $in_name /out $out_name_64-bit.exe $icon_param /silent verbose

    - name: Run Ahk2Exe_32-bit
      shell: pwsh
      run: Ahk2exe.exe /base "$cwd\_autohotkey\Compiler\AutoHotkey32.exe" /in $in_name /out $out_name_32-bit.exe $icon_param /silent verbose

branding:
  color: green
  icon: terminal
