name: Ahk2Exe
description: GitHub Action to compile AutoHotKey scripts using Ahk2Exe
author: nekocodeX, modified for ahk v2 by jaredkotoff

inputs:
  in:
    description: The path or file name of the AutoHotKey script to compile
    required: true
  out:
    description: The path or file name of the compiled executable (by default, an executable of the same name will be created in the path of the AutoHotKey script specified by the "in" parameter)
    required: false
    default: ''
  icon:
    description: The icon of the executable file is specified
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Install AutoHotkey
      shell: pwsh
      run: |
        $cwd = (Get-Item .).FullName;
        Expand-Archive -Path "$cwd\.github\actions\ahk2exe\ahk2exe-v1.1.35.00.zip" -DestinationPath "$cwd\_autohotkey\" -Force;
        Write-Output ("$cwd\_autohotkey\;" + "$cwd\_autohotkey\Compiler") | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        Copy-Item -Path "$cwd\_autohotkey\Compiler\Unicode 64-bit.bin" -Destination "$cwd\_autohotkey\Compiler\AutoHotkeySC.bin"
        Copy-Item -Path "$cwd\_autohotkey\Compiler\Unicode 64-bit.bin" -Destination "$cwd\_autohotkey\Compiler\AutoHotkeySC.bin"

    - name: Run Ahk2Exe_64-bit
      shell: pwsh
      run: |
        $command = 'ahk2exe.exe /silent verbose '
        $command += '/in "${{inputs.in}}" '
        if('${{inputs.out}}' -ne ''){
          $command += '/out "${{inputs.out}}_64-bit" '
        } else {
          $command += '/out "${{inputs.in}}_64-bit" '
        }
        if('${{inputs.icon}}' -ne ''){
          $command += '/icon "${{inputs.icon}}" '
        }
        $command += '/base "$cwd\_autohotkey\Compiler\AutoHotkey64.exe" '
        $command += "| Write-Output"
        Invoke-Expression $command

    - name: Run Ahk2Exe_32-bit
      shell: pwsh
      run: |
        $command = 'ahk2exe.exe /silent verbose '
        $command += '/in "${{inputs.in}}" '
        if('${{inputs.out}}' -ne ''){
          $command += '/out "${{inputs.out}}_32-bit" '
        } else {
          $command += '/out "${{inputs.in}}_32-bit" '
        }
        if('${{inputs.icon}}' -ne ''){
          $command += '/icon "${{inputs.icon}}" '
        }
        $command += '/base "$cwd\_autohotkey\Compiler\AutoHotkey32.exe" '
        $command += "| Write-Output"
        Invoke-Expression $command

branding:
  color: green
  icon: terminal
