name: Ahk2Exe

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:

jobs:
  Ahk2Exe:
    name: Ahk2Exe
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Ahk2Exe
        uses: ./.github/actions/ahk2exe
        with:
          in: afb

      - name: Release
        uses: softprops/action-gh-release@latest
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            afb_64-bit.exe
            afb_32-bit.exe
            afb.ahk
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}