name: Ahk2Exe

on:
  push:
    branches:
      - 'main'
      - 'gh-action'
    tags:
      - 'v*'
  pull_request:

jobs:
  Ahk2Exe:
    name: Ahk2Exe
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ahk2Exe
        uses: ./.github/actions/ahk2exe.yml
        with:
          in: afb.ahk

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: afb.exe
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}